version: "3.8"
services:
  mysql:
    #image: mysql:
    image: mysql:5.7.37
    container_name: mysql
    #environment:
    #  - MYSQL_ROOT_PASSWORD=password
    env_file:
      - mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  loki:
    image: grafana/loki:main
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
  prometheus:
    image: prom/prometheus:v2.46.0
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  tempo:
    image: grafana/tempo:2.2.2
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3110:3100"  # Tempo
      - "9411:9411" # zipkin
  grafana:
    image: grafana/grafana:10.1.0
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
  smtp:
    image: haravich/fake-smtp-server
    ports:
      - "1025:1025"
      - "1080:1080"


volumes:
  mongo-data:
    name: mongo-data
  mongo-config-data:
    name: mongo-data-configdb
  redis-data:
    name: redis-data
  mysql-data:
    name: mysql-data
